version: "3.8"

services:
  # Angular Frontend
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    command: npm run start
    volumes:
      - ./frontend:/thomas/frontend/src/app
      - /oykuparlak/frontend/src/app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - api
    environment:
      - PROXY_API_URL=http://api:3000  # Yeni eklenen environment değişkeni

  # NestJS Todo Api
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    volumes:
      - ./api:/oykuparlak/src/app
      - /oykuparlak/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 520741
      POSTGRES_DB: todo-app
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:6.12
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
